//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeOfDeath_MAUI.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeOfDeath_MAUI.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the weight of the body.
        /// </summary>
        internal static string Basic_BodyWeight {
            get {
                return ResourceManager.GetString("Basic_BodyWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date the body was found.
        /// </summary>
        internal static string Basic_DateFound {
            get {
                return ResourceManager.GetString("Basic_DateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What temperature was the body when found (deg C).
        /// </summary>
        internal static string Basic_TempFound {
            get {
                return ResourceManager.GetString("Basic_TempFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the temperature of the surrounds (deg C).
        /// </summary>
        internal static string Basic_TempSurrounds {
            get {
                return ResourceManager.GetString("Basic_TempSurrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time the body was found.
        /// </summary>
        internal static string Basic_TimeFound {
            get {
                return ResourceManager.GetString("Basic_TimeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate time of death.
        /// </summary>
        internal static string Cond_CalcButton {
            get {
                return ResourceManager.GetString("Cond_CalcButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry with more thin or thicker layers.
        /// </summary>
        internal static string Cond_Dry_More {
            get {
                return ResourceManager.GetString("Cond_Dry_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry with 1-2 thicker layers.
        /// </summary>
        internal static string Cond_Dry12Thick {
            get {
                return ResourceManager.GetString("Cond_Dry12Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry with 1-2 thin layers.
        /// </summary>
        internal static string Cond_Dry12Thin {
            get {
                return ResourceManager.GetString("Cond_Dry12Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry with 2-3 thin layers.
        /// </summary>
        internal static string Cond_Dry23Thin {
            get {
                return ResourceManager.GetString("Cond_Dry23Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry with 3-4 thin layers.
        /// </summary>
        internal static string Cond_Dry34Thin {
            get {
                return ResourceManager.GetString("Cond_Dry34Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry and naked.
        /// </summary>
        internal static string Cond_DryNaked {
            get {
                return ResourceManager.GetString("Cond_DryNaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When found, the body was.
        /// </summary>
        internal static string Cond_Found {
            get {
                return ResourceManager.GetString("Cond_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If found in air, the air was.
        /// </summary>
        internal static string Cond_FoundAir {
            get {
                return ResourceManager.GetString("Cond_FoundAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If pulled from water, the air was.
        /// </summary>
        internal static string Cond_FoundPulled {
            get {
                return ResourceManager.GetString("Cond_FoundPulled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If found in water, it was.
        /// </summary>
        internal static string Cond_FoundWater {
            get {
                return ResourceManager.GetString("Cond_FoundWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving.
        /// </summary>
        internal static string Cond_Move {
            get {
                return ResourceManager.GetString("Cond_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still.
        /// </summary>
        internal static string Cond_Still {
            get {
                return ResourceManager.GetString("Cond_Still", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Cond_Unknown {
            get {
                return ResourceManager.GetString("Cond_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulled from the water.
        /// </summary>
        internal static string Cond_WaterPull {
            get {
                return ResourceManager.GetString("Cond_WaterPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet with 1-2 thin wet layers.
        /// </summary>
        internal static string Cond_Wet12Thin {
            get {
                return ResourceManager.GetString("Cond_Wet12Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet with 2 or more thicker wet layers.
        /// </summary>
        internal static string Cond_Wet2More {
            get {
                return ResourceManager.GetString("Cond_Wet2More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet with 2 thicker wet layers.
        /// </summary>
        internal static string Cond_Wet2Thick {
            get {
                return ResourceManager.GetString("Cond_Wet2Thick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wet and naked.
        /// </summary>
        internal static string Cond_WetNaked {
            get {
                return ResourceManager.GetString("Cond_WetNaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body has to have some weight.
        /// </summary>
        internal static string Error_BodyWeight {
            get {
                return ResourceManager.GetString("Error_BodyWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature of surrounds is null.
        /// </summary>
        internal static string Error_CalcTempNull {
            get {
                return ResourceManager.GetString("Error_CalcTempNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator error.
        /// </summary>
        internal static string Error_CalcTitle {
            get {
                return ResourceManager.GetString("Error_CalcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature of the body is null.
        /// </summary>
        internal static string Error_TempBodyNull {
            get {
                return ResourceManager.GetString("Error_TempBodyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body temperature has to be higher than the surrounds.
        /// </summary>
        internal static string Error_TempDifference {
            get {
                return ResourceManager.GetString("Error_TempDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Gen_OK {
            get {
                return ResourceManager.GetString("Gen_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of death.
        /// </summary>
        internal static string Results_Date {
            get {
                return ResourceManager.GetString("Results_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death occured on or before .
        /// </summary>
        internal static string Results_OnBefore {
            get {
                return ResourceManager.GetString("Results_OnBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic info.
        /// </summary>
        internal static string Tabs_Basic {
            get {
                return ResourceManager.GetString("Tabs_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string Tabs_Conditions {
            get {
                return ResourceManager.GetString("Tabs_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Tabs_Results {
            get {
                return ResourceManager.GetString("Tabs_Results", resourceCulture);
            }
        }
    }
}
